# Generated by Django 3.0.8 on 2020-07-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200707_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_four_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_four_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_one_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_one_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_three_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_three_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_two_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='field_two_type',
        ),
        migrations.AddField(
            model_name='log',
            name='fields',
            field=models.ManyToManyField(to='app.Field'),
        ),
    ]
