# Generated by Django 3.0.8 on 2020-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200707_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('CHAR', 'Short text'), ('TEXT', 'Long text'), ('INT', 'Integer'), ('FLOAT', 'Floating point number')], default=None, max_length=5, null=True),
        ),
    ]
