# Generated by Django 3.0.8 on 2020-07-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('CF1', 'Short text field 1'), ('CF2', 'Short text field 2'), ('TF1', 'Long text field 1'), ('TF2', 'Long text field 2'), ('IF1', 'Integer field 1'), ('IF2', 'Integer field 2'), ('FF1', 'Floating point number field 1'), ('FF2', 'Floating point number field 2')], default=None, max_length=3, null=True),
        ),
    ]
