# Generated by Django 3.0.8 on 2020-07-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200707_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='char_field_one',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='char_field_three',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='char_field_two',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='float_field_one',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='float_field_three',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='float_field_two',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='int_field_one',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='int_field_three',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='int_field_two',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='text_field_one',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='text_field_three',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='text_field_two',
        ),
        migrations.AddField(
            model_name='entry',
            name='CF1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='CF2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='FF1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='FF2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='IF1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='IF2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='TF1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='TF2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
