# Generated by Django 3.0.3 on 2020-07-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200710_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fields',
            field=models.ManyToManyField(to='app.Field'),
        ),
    ]
