# Generated by Django 3.0.3 on 2020-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200711_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fields',
            field=models.ManyToManyField(blank=True, to='app.Field'),
        ),
    ]
