# Generated by Django 3.0.3 on 2020-07-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200713_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgementField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('CF1', 'Short text field 1'), ('CF2', 'Short text field 2'), ('CF3', 'Short text field 3'), ('CF4', 'Short text field 4'), ('CF5', 'Short text field 5'), ('CF6', 'Short text field 6'), ('CF7', 'Short text field 7'), ('CF8', 'Short text field 8'), ('CF9', 'Short text field 9'), ('CF10', 'Short text field 10'), ('TF1', 'Long text field 1'), ('TF2', 'Long text field 2'), ('TF3', 'Long text field 3'), ('TF4', 'Long text field 4'), ('TF5', 'Long text field 5'), ('IF1', 'Integer field 1'), ('IF2', 'Integer field 2'), ('IF3', 'Integer field 3'), ('IF4', 'Integer field 4'), ('IF5', 'Integer field 5'), ('FF1', 'Floating point number field 1'), ('FF2', 'Floating point number field 2'), ('FF3', 'Floating point number field 3'), ('FF4', 'Floating point number field 4'), ('FF5', 'Floating point number field 5')], default=None, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF8',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='CF9',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='FF3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='FF4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='FF5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='IF3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='IF4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='IF5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='TF3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='TF4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgement',
            name='TF5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='engineering_acknowledgement_fields',
            field=models.ManyToManyField(blank=True, related_name='engineering_acknowledgement_fields', to='app.AcknowledgementField'),
        ),
        migrations.AlterField(
            model_name='log',
            name='new_shift_acknowledgement_fields',
            field=models.ManyToManyField(blank=True, related_name='new_shift_acknowledgement_fields', to='app.AcknowledgementField'),
        ),
        migrations.AlterField(
            model_name='log',
            name='superintendent_acknowledgement_fields',
            field=models.ManyToManyField(blank=True, related_name='superintendent_acknowledgement_fields', to='app.AcknowledgementField'),
        ),
        migrations.AlterField(
            model_name='log',
            name='unit_lead_acknowledgement_fields',
            field=models.ManyToManyField(blank=True, related_name='unit_lead_acknowledgement_fields', to='app.AcknowledgementField'),
        ),
    ]
