# Generated by Django 3.0.3 on 2020-07-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200714_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tracked',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('UR', 'Unresolved'), ('IP', 'In progress'), ('RE', 'Resolved')], default=None, max_length=2, null=True),
        ),
    ]
