# Generated by Django 3.0.3 on 2020-07-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200714_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tracked',
            new_name='is_tracked',
        ),
    ]
