# Generated by Django 3.0.3 on 2020-07-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200714_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('UR', 'Unresolved'), ('IP', 'In progress'), ('RE', 'Resolved')], default='UR', max_length=2, null=True),
        ),
    ]
