# Generated by Django 3.0.3 on 2020-07-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200714_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='shown_in_table',
            field=models.BooleanField(default=True),
        ),
    ]
