# Generated by Django 3.0.3 on 2020-07-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_field_shown_in_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='for_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
