# Generated by Django 3.0.3 on 2020-07-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_acknowledgement_for_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
