# Generated by Django 3.0.3 on 2020-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200725_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('UR', 'Unresolved'), ('IP', 'In progress'), ('RE', 'Resolved'), ('AP', 'Approved'), ('CA', 'Cancelled')], default='None', max_length=2, null=True),
        ),
    ]
